version: 0.2

phases:
  install:
    commands:
      - echo "Installing Ubuntu Packages"
      - npm install express
  build:
    commands:
      - echo "Creating zip"
      - zip -r function.zip *
      - ls -al
  post_build:
    commands:
      - echo "creating lambda"
      - aws lambda update-function-code --function-name function --zip-file fileb://function.zip
artifacts:
  files:
    - build-output.zip
  discard-paths: no
